from typing import Any, Optional, Protocol

from .models import (
    AnchorHandle,
    AnchorResolution,
    CalloutSpec,
    DemoSpec,
    InteractionSpec,
    SurfaceSpec,
)


class NavigationPort(Protocol):
    def navigate(self, surface: SurfaceSpec, *, session_id: str, generation: int, request_id: str) -> None: ...
    def current_surface(self) -> SurfaceSpec: ...
    def cancel_pending(self) -> None: ...


class AnchorRegistryPort(Protocol):
    def resolve(self, anchor_id: str) -> AnchorResolution: ...


class InteractionObserverPort(Protocol):
    def bind(self, anchor: AnchorHandle, interaction: InteractionSpec, *, session_id: str, generation: int) -> Any: ...
    def unbind(self) -> None: ...
    def is_bound(self) -> bool: ...


class SpotlightPort(Protocol):
    def attach_host(self, host: Any) -> bool: ...
    def detach_host(self) -> None: ...
    def show_target(self, anchor: AnchorHandle, callout: CalloutSpec, controls: Any) -> bool: ...
    def show_info_without_target(self, callout: CalloutSpec, controls: Any) -> None: ...
    def show_demo(self, demo: DemoSpec, callout: CalloutSpec, controls: Any) -> bool: ...
    def show_recovery(self, message: str, *, retry_enabled: bool, skip_enabled: bool) -> None: ...
    def hide_step(self) -> None: ...


class DialogObserverPort(Protocol):
    def start(self, session_id: str) -> None: ...
    def stop(self) -> None: ...
    def active_modal_handle(self) -> Optional[str]: ...


class ProgressStorePort(Protocol):
    def is_completed(self, guide_id: str, content_version: int) -> bool: ...
    def is_dismissed(self, guide_id: str, content_version: int) -> bool: ...
    def mark_completed(self, guide_id: str, content_version: int) -> bool: ...
    def mark_dismissed(self, guide_id: str, content_version: int) -> bool: ...


# Compatibility aliases for the initial A3 draft names.
NavigationAdapterPort = NavigationPort
SpotlightLayerPort = SpotlightPort
DialogLifecycleObserverPort = DialogObserverPort
TourProgressStorePort = ProgressStorePort
