from dataclasses import dataclass, field
from typing import List, Optional
from core.subtitle_placement import SubtitlePlacementState

@dataclass
class WorkspaceState:
    active_page: str = "dashboard"
    active_tab: str = "inline_editor"
    selected_segment_id: Optional[str] = None
    playback_position_ms: int = 0
    subtitle_preview_enabled: bool = True
    splitter_sizes: list[int] = field(default_factory=lambda: [400, 200])

# --- [SPRINT 7.1] TIMING STATE ---
@dataclass
class TimingState:
    """Trạng thái Runtime của tiến trình Timing trong dự án"""
    # Project-level Timing preferences. Defaults preserve the current panel
    # behavior and make legacy state files load without a migration write.
    model_size: str = "large-v3-turbo"
    compute_type: str = "float16"
    use_vad: bool = True
    min_silence_ms: int = 500
    fix_overlap: bool = True
    overlap_gap_ms: int = 50
    overlap_ms: int = 800
    max_window_ms: int = 120000

    status: str = "IDLE"  # IDLE, RUNNING, COMPLETED, FAILED
    batch_size: int = 10
    next_segment_index: int = 1
    completed_until: int = 0
    timing_artifact_id: Optional[str] = None
    checkpoint_id: Optional[str] = None
# ---------------------------------

@dataclass
class ProjectState:
    task_mode: str = "asr"
    timing_status: str = "EMPTY"  
    text_status: str = "EMPTY"    
    export_status: str = "EMPTY"  
    
    active_artifact_id: Optional[str] = None
    # Canonical subtitle artifact generated by Sprint 9.
    subtitle_artifact_id: Optional[str] = None
    selected_segment_id: Optional[str] = None
    dirty: bool = False

    subtitle_placement: SubtitlePlacementState = field(default_factory=SubtitlePlacementState)
    
    workspace: WorkspaceState = field(default_factory=WorkspaceState)
    
    # [SPRINT 7.1] Nhúng TimingState
    timing: TimingState = field(default_factory=TimingState)
