from dataclasses import dataclass, field
from typing import List, Optional

@dataclass
class WorkspaceState:
    active_page: str = "dashboard"
    active_tab: str = "inline_editor"
    selected_segment_id: Optional[str] = None
    playback_position_ms: int = 0
    subtitle_preview_enabled: bool = True
    splitter_sizes: list[int] = field(default_factory=lambda: [400, 200])

# --- [SPRINT 7.1] TIMING STATE ---
@dataclass
class TimingState:
    """Trạng thái Runtime của tiến trình Timing trong dự án"""
    status: str = "IDLE"  # IDLE, RUNNING, COMPLETED, FAILED
    batch_size: int = 10
    next_segment_index: int = 1
    completed_until: int = 0
    timing_artifact_id: Optional[str] = None
    checkpoint_id: Optional[str] = None
# ---------------------------------

@dataclass
class ProjectState:
    timing_status: str = "EMPTY"  
    text_status: str = "EMPTY"    
    export_status: str = "EMPTY"  
    
    active_artifact_id: Optional[str] = None
    # Canonical subtitle artifact generated by Sprint 9.
    subtitle_artifact_id: Optional[str] = None
    selected_segment_id: Optional[str] = None
    dirty: bool = False
    
    workspace: WorkspaceState = field(default_factory=WorkspaceState)
    
    # [SPRINT 7.1] Nhúng TimingState
    timing: TimingState = field(default_factory=TimingState)
